baseURL = 'https://matheuslemos.com/'
language = "en"
title = 'Matheus Lemos - Engenheiro de Dados'
theme = 'data-engineer-portfolio'

[params]
  name = 'Matheus Lemos'
  role = 'Data Engineer'
  description = 'Senior Data Engineer with experience in Databricks, Spark and Delta Lake, ready to tackle your data problems'
  email = 'matheuslemosf@gmail.com'
  profile_image = 'img/profile.png'

[params.social]
  github = 'https://github.com/mlemosf'
  twitter = '#'
